language: node_js

node_js:

- 8.4.0

after_script:

- scp  -o  StrictHostKeyChecking=no ./build/app.js  root@47.94.168.174:/~/test/

before_install:
 - openssl aes-256-cbc -K $encrypted_3889bd0df4a7_key -iv $encrypted_3889bd0df4a7_iv
-in qxm_key.enc -out qxm_key -d













